name: Deploy Astro site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "." # default value when not using subfolders
  # BUILD_PATH: subfolder

jobs:
  build:
    env:
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      PUBLIC_SERVICE_KEY: ${{ secrets.PUBLIC_SERVICE_KEY }}
      PUBLIC_TEMPLATE_KEY: ${{ secrets.PUBLIC_TEMPLATE_KEY }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Secret Verification
        run: |
          echo "one: ${#env.PUBLIC_KEY}"
          echo "two: ${#env.PUBLIC_SEVICE_KEY}"
          echo "three: ${#env.PUBLIC_TEMPLATE_KEY}"
          exit 0
      - name: Checkout
        uses: actions/checkout@v6
      - name: Detect package manager
        id: detect-package-manager
        run: |
          echo "manager=bun" >> $GITHUB_OUTPUT
          echo "command=install" >> $GITHUB_OUTPUT
          echo "runner=bun" >> $GITHUB_OUTPUT
          echo "lockfile=bun.lock" >> $GITHUB_OUTPUT
          exit 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
        working-directory: ${{ env.BUILD_PATH }}
      - name: Build with Astro
        run: |
          ${{ steps.detect-package-manager.outputs.runner }} astro build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.BUILD_PATH }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
